label: Media
display:
  default:
    display_title: Główny
    display_options:
      exposed_form:
        options:
          submit_button: Zastosuj
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      pager:
        options:
          expose:
            items_per_page_label: 'Elementów na stronę'
            items_per_page_options_all_label: '- Wszystko -'
            offset_label: Przesunięcie
      fields:
        media_bulk_form:
          action_title: Akcja
        thumbnail__target_id:
          label: Miniaturka
        bundle:
          label: Usługodawca
        uid:
          label: Autor
        status:
          label: Status
        changed:
          label: Uaktualniono
        operations:
          label: Operacje
      filters:
        status:
          expose:
            label: Prawda
          group_info:
            label: 'Status opublikowania'
            group_items:
              1:
                title: Opublikowane
                value: '1'
              2:
                title: Nieopublikowany
        bundle:
          expose:
            label: Usługodawca
        langcode:
          expose:
            label: Język
      title: Media
      empty:
        area_text_custom:
          content: 'Brak zawartości.'
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
