label: 'Media Library'
description: 'Listing of all the media items available.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: Bundle
        status:
          expose:
            label: 'Publishing status'
      sorts:
        created:
          expose:
            label: Created
        name:
          expose:
            label: 'Media name'
      title: 'Media Library'
  gallery_media_select_modal:
    display_title: 'Gallery media select modal'
    display_options:
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: Bundle
        bundle_1:
          expose:
            label: Bundle
        status:
          expose:
            label: 'Publishing status'
      display_description: 'An entity browser modal to select media while creating gallery.'
  gallery_user_media_select_modal:
    display_title: 'Gallery User Media select modal'
    display_options:
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: Bundle
        bundle_1:
          expose:
            label: Bundle
        status:
          expose:
            label: 'Publishing status'
      display_description: 'An entity browser modal to select user media while creating gallery'
      arguments:
        uid:
          exception:
            title: All
  global_media_library_page:
    display_title: 'Gobal Media Library'
    display_options:
      menu:
        title: Media
        description: 'Displays the media items'
      display_description: 'View for the global media library.'
      fields:
        bundle:
          label: Type
          separator: ', '
        status:
          label: Status
          separator: ', '
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: Bundle
        status:
          expose:
            label: 'Publishing status'
        langcode:
          expose:
            label: Language
      title: 'Media Library'
  media_select_modal:
    display_title: 'Media select modal'
    display_options:
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: Bundle
        status:
          expose:
            label: 'Publishing status'
      display_description: 'An entity browser modal to select media.'
  user_media_library:
    display_title: 'User Media Library'
    display_options:
      menu:
        title: Media
        description: 'Displays the media items by the user'
      arguments:
        uid:
          exception:
            title: All
      display_description: 'A page on the user profile to display media items by the user.'
      fields:
        bundle:
          label: Type
          separator: ', '
        status:
          label: Status
          separator: ', '
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: Bundle
        status:
          expose:
            label: 'Publishing status'
        langcode:
          expose:
            label: Language
  user_media_select_modal:
    display_title: 'User Media select modal'
    display_options:
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: Bundle
        status:
          expose:
            label: 'Publishing status'
      display_description: 'An entity browser modal to select user media'
      arguments:
        uid:
          exception:
            title: All
